### ISSUE TITLE
Installing poisson-etest doesn't work 

### ISSUE THREAD

**Issue by LangeTo** [nolanbconaway/poisson-etest#2]
Hi, 

I would like to use the Poisson-etest package to compare my datasets but I can't install the package, can someone help me out (I'm not really experienced in programming)? 

When I try to install via the PyCharm Termin using pip install poisson-etest, I get this error:  _extension 'poisson_etest.poisson_etest_fortran' has Fortran sources but no Fortran compiler found_.
So I guess I need to install Fortran which I tried as suggested here: https://github.com/NickHilton/poisson-etest (brew install gcc) but then I get the error: _The command "brew" is either misspelled or could not be found._

How can I now install Fortran and the poisson-etest package? 

Cheers, 
Tobi

**Comment by nolanbconaway** [comment]
Hi! were you able to install numpy first? If so, then you've just got to install gcc. Brew is a macos/linux thing, so if you're on windows you might need to install gcc another way (can't help you there). If all else fails, I have a branch of this repo which runs on pure python. It's slower but has no dependencies!

```sh
pip install git+https://github.com/nolanbconaway/poisson-etest.git@purepy 
```

Let me know if any of these tips are helpful!

**Comment by LangeTo** [comment]
Yes, numpy was already installed and it worked perfectly to install the package via pip install git+http.....
Thank you very much :-) 

Cheers!
