### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by aojielian** [nolanbconaway/poisson-etest#3]
Hi Nolan,
I want to use this code to count the P value, But when i install your package, i met these error:
 ERROR: Command errored out with exit status 1:
     command: /zs32/home/a1lian/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w5049sut/poisson-etest/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w5049sut/poisson-etest/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_ad47rto
         cwd: /tmp/pip-install-w5049sut/poisson-etest/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w5049sut/poisson-etest/setup.py", line 1, in <module>
        from numpy.distutils.core import Extension
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Would you please tell me  how can i fix this problem?
Thanks,
Aojie

**Comment by nolanbconaway** [comment]
Hi! I packaged this is not a great way; but you should be able to install after you get numpy installed!

**Comment by aojielian** [comment]
Hi Nolan, thanks for your reply.
I used conda to install numpy first
$ python -c "import numpy; print(numpy.version.version)"
1.21.2
And then run "pip install poisson-etest", But it still can not install it,Below is the error shows:
Collecting poisson-etest
  Using cached poisson_etest-0.0.tar.gz (3.0 kB)
Building wheels for collected packages: poisson-etest
  Building wheel for poisson-etest (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/a1lian/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-600rljca/poisson-etest_9fa0162f8ee0438da81765708a3ed447/setup.py'"'"'; __file__='"'"'/tmp/pip-install-600rljca/poisson-etest_9fa0162f8ee0438da81765708a3ed447/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o61gzupo
       cwd: /tmp/pip-install-600rljca/poisson-etest_9fa0162f8ee0438da81765708a3ed447/
  Complete output (177 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "poisson_etest.poisson_etest_fortran" sources
  f2py options: []
    adding 'build/src.linux-x86_64-3.9/build/src.linux-x86_64-3.9/poisson_etest/fortranobject.c' to sources.
    adding 'build/src.linux-x86_64-3.9/build/src.linux-x86_64-3.9/poisson_etest' to include_dirs.
    adding 'build/src.linux-x86_64-3.9/poisson_etest/poisson_etest_fortran-f2pywrappers.f' to sources.
  build_src: building npy-pkg config files
  running build_py
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/poisson_etest
  copying lib/__init__.py -> build/lib.linux-x86_64-3.9/poisson_etest
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  CCompilerOpt.cc_test_flags[1013] : testing flags (-march=native)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  creating /tmp/tmputk6t62b/home
  creating /tmp/tmputk6t62b/home/a1lian
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils
  creating /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-march=native'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -march=native) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.cc_test_flags[1013] : testing flags (-O3)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-O3'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -O3) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.cc_test_flags[1013] : testing flags (-Werror)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-Werror'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -Werror) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.__init__[1701] : check requested baseline
  CCompilerOpt.cc_test_flags[1013] : testing flags (-msse)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-msse'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -msse) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.cc_test_flags[1013] : testing flags (-msse2)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-msse2'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -msse2) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.feature_test[1466] : testing feature 'SSE' with flags ()
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse.o.d) failed with exit status 127 output ->
  b''
  CCompilerOpt.feature_test[1482] : testing failed
  CCompilerOpt.feature_test[1466] : testing feature 'SSE2' with flags ()
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse2.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse2.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse2.o.d) failed with exit status 127 output ->
  b''
  CCompilerOpt.feature_test[1482] : testing failed
  CCompilerOpt.__init__[1710] : check requested dispatch-able features
  CCompilerOpt.cc_test_flags[1013] : testing flags (-msse3)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-msse3'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -msse3) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.cc_test_flags[1013] : testing flags (-mssse3)
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  extra options: '-mssse3'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -mssse3) failed with exit status 127 output ->
  b''
  CCompilerOpt.cc_test_flags[1017] : testing failed
  CCompilerOpt.feature_test[1466] : testing feature 'SSSE3' with flags ()
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_ssse3.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_ssse3.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_ssse3.o.d) failed with exit status 127 output ->
  b''
  CCompilerOpt.feature_test[1482] : testing failed
  CCompilerOpt.feature_test[1466] : testing feature 'SSE3' with flags ()
  C compiler: gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC
  
  compile options: '-I/home/a1lian/anaconda3/include/python3.9 -c'
  CCompilerOpt.dist_test[581] : CCompilerOpt._dist_test_spawn[716] : Command (gcc -pthread -B /home/a1lian/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/a1lian/anaconda3/include -I/home/a1lian/anaconda3/include -fPIC -O2 -isystem /home/a1lian/anaconda3/include -fPIC -I/home/a1lian/anaconda3/include/python3.9 -c /home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse3.c -o /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse3.o -MMD -MF /tmp/tmputk6t62b/home/a1lian/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_sse3.o.d) failed with exit status 127 output ->
  b''
  CCompilerOpt.feature_test[1482] : testing failed
  CCompilerOpt.__init__[1726] : initialize targets groups
  CCompilerOpt.__init__[1728] : parse target group simd_test
  CCompilerOpt._parse_target_tokens[1939] : skip targets (XOP FMA4 SSE42 AVX512F VSX3 SSE2 VSX2 ASIMD (FMA3 AVX2) VSX NEON AVX512_SKX) not part of baseline or dispatch-able features
  CCompilerOpt.generate_dispatch_header[2272] : generate CPU dispatch header: (build/src.linux-x86_64-3.9/numpy/distutils/include/npy_cpu_dispatch_config.h)
  CCompilerOpt.generate_dispatch_header[2281] : dispatch header dir build/src.linux-x86_64-3.9/numpy/distutils/include does not exist, creating it
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'nv', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor', 'fujitsu']'
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize IntelFCompiler
  Could not locate executable ifort
  Could not locate executable ifc
  customize LaheyFCompiler
  Could not locate executable lf95
  customize PGroupFCompiler
  Could not locate executable pgfortran
  customize NVHPCFCompiler
  Could not locate executable nvfortran
  customize AbsoftFCompiler
  Could not locate executable f90
  Could not locate executable f77
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  Could not locate executable fort
  customize IntelItaniumFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  Could not locate executable g77
  customize G95FCompiler
  Could not locate executable g95
  customize PathScaleFCompiler
  Could not locate executable pathf95
  customize NAGFORCompiler
  Could not locate executable nagfor
  customize FujitsuFCompiler
  Could not locate executable frt
  don't know how to compile Fortran code on platform 'posix'
  warning: build_ext: f77_compiler=None is not available.
  
  building 'poisson_etest.poisson_etest_fortran' extension
  error: extension 'poisson_etest.poisson_etest_fortran' has Fortran sources but no Fortran compiler found
  
  ########### EXT COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none
  
  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  CCompilerOpt.cache_flush[809] : write cache to path -> /tmp/pip-install-600rljca/poisson-etest_9fa0162f8ee0438da81765708a3ed447/build/temp.linux-x86_64-3.9/ccompiler_opt_cache_ext.py
  ----------------------------------------
  ERROR: Failed building wheel for poisson-etest

**Comment by nolanbconaway** [comment]
Ah right; numpy is wrapping fortran here, and it looks like your interpreter can't find a fortran installation!

```
building 'poisson_etest.poisson_etest_fortran' extension
error: extension 'poisson_etest.poisson_etest_fortran' has Fortran sources but no Fortran compiler found
```

I don't know your OS, but here's the invocation on ubuntu:

```
sudo apt-get install gfortran
```

**Comment by aojielian** [comment]
COOL, Thanks
